### ISSUE TITLE
how does one get the filename of the current progress when uploading multiple files?

### ISSUE THREAD

**Issue by phil123456** [DarkXaHTeP/angular-progress-http#20]
Hello,

I checked the data received in the progress listener but the path is not populated

thanks

**Comment by DarkXaHTeP** [comment]
@phil123456, I'm not sure that this functionality should be a part of the library, because it works on higher level of abstraction (e.g. treats request/response as a single entity that has size and percent uploaded/downloaded). In case you want to get access to the file, you can do it like I did in one of the examples [here](https://github.com/DarkXaHTeP/angular-progress-http/blob/f02bc303e5f5b5dc470c354e9f4d15bc17306407/examples/upload-download/src/app/app.component.ts#L32-L40)
Could you please share a more detailed use-case for this property or let me know if the solution proposed above satisfies your needs, so that I close this issue? Thanks!

**Comment by phil123456** [comment]
one can upload multiple files, so if one get the percents, an additional value should be passed to know at least the index of the file, if not the file name itself

I just used one of your example that I adapted for my needs

```
    private upload(command:string,params:any,files: File[],router:Router): Observable <any>
    {
        let formData: FormData = new FormData();

        for (let i = 0; i < files.length; i++) {
            formData.append("uploads[]", files[i], files[i].name);
        }

        let options = this.createPostOptionsForUploads();

        return this.progressHttp
            .withUploadProgressListener(progress => {
                    console.log("progress: "+progress.percentage);
                    this.progressObserver.next(progress.percentage);
                })
            .post(this.createURL(command+'&'+Tools.makeParams(params,false)), formData, options)
            .map((response: Response) => this.processData(response,router));
            //.catch(error => Observable.throw(error));
    }
```

**Comment by DarkXaHTeP** [comment]
@phil123456, now I get it. You should upload each file as a separate request to know it's progress. Otherwise you'll get a progress of the whole request - all files. This is the default behavior of XMLHttpRequest and cannot be changed. Take a look at [the example from my comment above](https://github.com/DarkXaHTeP/angular-progress-http/blob/f02bc303e5f5b5dc470c354e9f4d15bc17306407/examples/upload-download/src/app/app.component.ts#L32-L40) one more time

**Comment by phil123456** [comment]
ok 
too bad
thx :-)
