### ISSUE TITLE
Upload progress not accurate

### ISSUE THREAD

**Issue by sjsource** [DarkXaHTeP/angular-progress-http#28]
Hi thanks for awesome work,
The download works as sweet
But for the upload, it shows the progress of upload but only after showing 100% percentage uploaded, it is hitting API and then API takes more time to send response back to client which makes as non-realistic progress

I am using Angular 5, .Net core API

Can you throw some light?

**Comment by DarkXaHTeP** [comment]
@sjsource it turns out that there is a built-in throttling for the 'progress' event in XMLHttpRequest that we cannot prevent from happening. To test that your upload progress works correctly either try uploading big files or turn on "Slow 3G" preset on Network tab of Chrome Developer Tools (I would recommend doing both)
