### ISSUE TITLE
Issue loading with SystemJs

### ISSUE THREAD

**Issue by lsholubka** [DarkXaHTeP/angular-progress-http#6]
Hi, I have issue trying to load it with SystemJs. Here is excerpt from my SystemJs config:

paths: {
     'npm:': 'node_modules/'
},
map: {
    'angular-progress-http': 'npm:angular-progress-http'
},
packages: {
    'angular-progress-http': {
        main: 'index.js',
        defaultExtension: 'js'
    }
}

I'm getting following error in browser:

Error: Unable to dynamically transpile ES module A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`. Instantiating http://localhost:8090/node_modules/angular-progress-http/index.js

Do you have example working with SystemJs loader?

**Comment by DarkXaHTeP** [comment]
@lsholubka Unfortunately, I'm not very familiar with SystemJS. In my work I use mostly Angular CLI and Webpack. Could you please provide some example project so that I'll be able to reproduce issue and test a solution if any? Also there are two more things:
1) as far as I know, there is a common practice to add UMD bundle to the library to support SystemJS. Unfortunately, my lib doesn't have it at the moment. Added it as an action item for the future versions
2) did it work on previous versions (before 0.5.0)? If yes, you still may use *.ts files by referencing "angular-progress-http/ts/index.ts" in your SystemJS config

**Comment by DarkXaHTeP** [comment]
SystemJS support is added in v1.0.0
